services:
  - type: web
    name: proresume-api
    runtime: node
    plan: free
    buildCommand: npm install --prefix backend
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: ADMIN_EMAIL
        value: nejamulhaque.works@gmail.com
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
